logging:
  file:
    name: app_gateway.log

server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
  port: 8443
  address: 0.0.0.0

spring:
  main:
    web-application-type: REACTIVE

  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://auth-service:5500
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthFilter

        - id: resource_service
          uri: http://resource-service:5501
          predicates:
            - Path=/api/v1/resources/**
          filters:
            - AuthFilter

        - id: channel_service
          uri: http://channel-service:5502
          predicates:
            - Path=/api/v1/channels/**
          filters:
            - AuthFilter

        - id: friend_service
          uri: http://channel-service:5502
          predicates:
            - Path=/api/v1/friends/**
          filters:
            - AuthFilter

        - id: message_service
          uri: http://channel-service:5502
          predicates:
            - Path=/api/v1/messages/**
          filters:
            - AuthFilter

        - id: user_service
          uri: http://channel-service:5502
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthFilter

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Acess-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true

