logging:
  file:
    name: app.log

server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
  port: 8443
  address: 0.0.0.0

spring:
  main:
    web-application-type: REACTIVE

  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:5500
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthFilter

        - id: resource_service
          uri: http://localhost:5501
          predicates:
            - Path=/api/v1/resource/**
          filters:
            - AuthFilter

        - id: friend_service
          uri: http://localhost:5502
          predicates:
            - Path=/api/v1/friend/**
          filters:
            - AuthFilter

        - id: channel_service
          uri: http://localhost:5502
          predicates:
            - Path=/api/v1/channel/**
          filters:
            - AuthFilter

        - id: message_service
          uri: http://localhost:5502
          predicates:
            - Path=/api/v1/message/**
          filters:
            - AuthFilter

        - id: user_service
          uri: http://localhost:5502
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthFilter

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Acess-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

