-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgiHAw+iIrMepw4sA+
rm4xs1L98OBBHYD36NI5bNIABJGgCgYIKoZIzj0DAQehRANCAASkuLnWmBVsV0SA
ioqmg7Kn5GSb/VdqHHrgPDRQHnW9yLYAlR4bMaW1HJXLK6SYz36XRvWV8fJTiBjI
XB8jc3Ae
-----END PRIVATE KEY-----